services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gradebookdb'
      - 'POSTGRES_PASSWORD=perspers08'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    volumes:
      - '/run/desktop/mnt/host/c/Users/ulana/IdeaProjects/gradebook-coursework-main/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro'